# More options: https://getcockpit.com/documentation/reference/configuration

debug: true

app.name: Strona_KSI

languages:
    # en: English (Default)
    pl: Polish
    uk: Ukrainian

groups:
    editor:
        $admin: false
        $vars:
            finder.path: /storage/upload
        cockpit:
            backend: true
            finder: true
