version: '3'

volumes:
  storage:

services:
  backend:
    build: ./backend
    volumes:
      - storage:/var/www/html/storage

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      API_URL: ${API_URL}

  caddy:
    image: abiosoft/caddy
    environment:
      ACME_AGREE: 'true'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy/.caddy:/root/.caddy
      - /var/www/html/:/var/www/html