# Cockpit-CMS image
FROM kamarkiewicz/cockpitcms

# Locally-built base image
# FROM cockpitcms

ADD --chown=www-data:www-data config /var/www/html/config/
ADD --chown=www-data:www-data addons /var/www/html/addons/
