version: '3.1'

services:
  squidex:
    restart: unless-stopped
    image: squidex/squidex:latest
    volumes:
      - squidexkeys:/etc/squidex/keys
    ports:
      - '5000:80'
    environment:
      - 'URLS__BASEURL=https://${SQUIDEX_DOMAIN}/'
      - 'URLS__ENFORCEHTTPS=True'
      - 'EVENTSTORE__CONSUME=true'
      - 'EVENTSTORE__MONGODB__CONFIGURATION=mongodb://mongo'
      - 'STORE__MONGODB__CONFIGURATION=mongodb://mongo'
      - 'IDENTITY__KEYSSTORE__TYPE=Folder'
      - 'IDENTITY__KEYSSTORE__FOLDER=/etc/squidex/keys'
      - 'IDENTITY__ADMINEMAIL=${SQUIDEX_ADMINEMAIL}'
      - 'IDENTITY__ADMINPASSWORD=${SQUIDEX_ADMINPASSWORD}'
      - 'IDENTITY__GITHUBCLIENT='
      - 'IDENTITY__GITHUBSECRET='
      - 'IDENTITY__GOOGLECLIENT='
      - 'IDENTITY__GOOGLESECRET='
      - 'IDENTITY__MICROSOFTCLIENT='
      - 'IDENTITY__MICROSOFTSECRET='
      - 'LETSENCRYPT_HOST=${SQUIDEX_DOMAIN}'
      - 'LETSENCRYPT_EMAIL=${SQUIDEX_ADMINEMAIL}'
      - 'VIRTUAL_HOST=${SQUIDEX_DOMAIN}'
    depends_on:
      - mongo

  mongo:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - mongodb:/data/db

volumes:
  squidexkeys:
  mongodb:
